#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MonkeyFly.MES.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EquipmentManagement/EMS00008MaintenanceList.cshtml")]
    public partial class _Views_EquipmentManagement_EMS00008MaintenanceList_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_EquipmentManagement_EMS00008MaintenanceList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\EquipmentManagement\EMS00008MaintenanceList.cshtml"
  
    ViewBag.Title = "EMS00008MaintenanceList";
    Layout = "~/Views/Shared/_LayoutLang.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tb_list\"");

WriteLiteral(" class=\"J-main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"J-toolbar\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" id=\"btn_refresh\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"Refresh\"");

WriteLiteral(" onclick=\"model.refreshClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-arrow_refresh\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Refresh\"");

WriteLiteral("> Refresh</span></button>\r\n        <button");

WriteLiteral(" id=\"btn_search\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"Search\"");

WriteLiteral(" onclick=\"model.searchClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral("> Search</span></button>\r\n        <button");

WriteLiteral(" id=\"btn_save\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"Save\"");

WriteLiteral(" onclick=\"model.saveClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-save\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Save\"");

WriteLiteral("> Save</span></button>\r\n        <button");

WriteLiteral(" id=\"btn_add\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"New\"");

WriteLiteral(" onclick=\"model.addClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-add\"");

WriteLiteral("></i><span");

WriteLiteral(" data-meaning=\"New\"");

WriteLiteral("> Add</span></button>\r\n        <button");

WriteLiteral(" id=\"btn_edit\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"Change\"");

WriteLiteral(" onclick=\"model.editClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-edit\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Change\"");

WriteLiteral("> Edit</span></button>\r\n        <button");

WriteLiteral(" id=\"btn_delete\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"Deletion\"");

WriteLiteral(" onclick=\"model.deleteClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-delete\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Deletion\"");

WriteLiteral("> Delete</span></button>\r\n        <button");

WriteLiteral(" id=\"btn_languages\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"Langwage\"");

WriteLiteral(" onclick=\"model.languagesClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-language\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Langwage\"");

WriteLiteral("> Languages</span></button>\r\n        <button");

WriteLiteral(" id=\"btn_import\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"Import\"");

WriteLiteral(" onclick=\"model.importClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-page_white_excel\"");

WriteLiteral("></i><span");

WriteLiteral(" data-meaning=\"Import\"");

WriteLiteral("> Import</span></button>\r\n        <button");

WriteLiteral(" id=\"btn_export\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" title=\"Export\"");

WriteLiteral(" onclick=\"model.exportClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-download\"");

WriteLiteral("></i><span");

WriteLiteral(" data-meaning=\"Export\"");

WriteLiteral("> Export</span></button>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" data-meaning=\"MaintenanceLists\"");

WriteLiteral(">Maintenance Lists</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MaintenanceItem\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral(" data-bind=\"value: MaintenanceItem\"");

WriteLiteral(" />\r\n        &nbsp;&nbsp;\r\n        <span");

WriteLiteral(" data-meaning=\"MaintenanceListsDescription\"");

WriteLiteral(">Maintenance Lists Description</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MaintenanceDescription\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral(" data-bind=\"value: MaintenanceDescription\"");

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-content\"");

WriteLiteral(" id=\"table-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"MainContent\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" id=\"MaintenanceListTable\"");

WriteLiteral("></table>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionBar\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ImportDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <style>\r\n        .ui-state-highlight, .ui-widget-content .ui-state-highlig" +
"ht, .ui-widget-header .ui-state-highlight {\r\n            border: 1px solid red;\r" +
"\n        }\r\n    </style>\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:400px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\"font-size:20px\"");

WriteLiteral(" data-meaning=\"Import\"");

WriteLiteral(">Import</span>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div>\r\n                    <div>\r\n                        <but" +
"ton");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"BtnBrowse\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" data-meaning=\"Browse\"");

WriteLiteral(">Browse</span>\r\n                        </button>\r\n                        <input" +
"");

WriteLiteral(" id=\"BtnFile\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" style=\"opacity:0\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" style=\"padding:5px;\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" id=\"FileName\"");

WriteLiteral("></span>\r\n                    </div>\r\n                </div>\r\n            </div>\r" +
"\n            <div");

WriteLiteral(" style=\"text-align:right;padding:5px 10px;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"BtnImport\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(">Comfirm</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"DetailDialog\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:850px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:5px 10px 5px 5px  !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Shut</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"Details\"");

WriteLiteral("> Details</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"padding: 0px 5px 2px!important\"");

WriteLiteral(" id=\"table_body_process_data\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"DetailTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"paginagionDetailBar\"");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" style=\"padding-bottom:5px!important\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" style=\"text-align:right;padding:5px 10px;\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" ");

WriteLiteral(" >Cancel</button>\r\n                    <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"New\"");

WriteLiteral("    onclick=\"model.DetailNewClick()\"");

WriteLiteral(">New</button>\r\n\r\n                </div>\r\n           \r\n        </div>\r\n    </div>\r" +
"\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"DeviceDialog\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:850px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:5px 10px 5px 5px  !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Shut</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"MaintenanceListsEquipment\"");

WriteLiteral("> Maintenance Lists Equipment</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(" style=\"padding:5px\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"EquipmentCode\"");

WriteLiteral(">Equipment Code</span>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DeviceDialogEquipmentCode\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral("/>\r\n                &nbsp;&nbsp;\r\n                <span");

WriteLiteral(" data-meaning=\"EquipmentDescription\"");

WriteLiteral(">Equipment Description</span>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DeviceDialogEquipmentDescription\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral("  class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DeviceDialogSearch()\"");

WriteLiteral("  data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"padding: 0px 5px 2px!important\"");

WriteLiteral(" id=\"table_body_process_data\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"DeviceTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"paginagionDeviceBar\"");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" style=\"padding-bottom:5px!important\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"padding: 5px !important\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"text-align:right;padding:5px 10px;\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" >Close</button>\r\n\r\n                    <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"New\"");

WriteLiteral(" onclick=\"model.DeviceNewClick()\"");

WriteLiteral(">New</button>\r\n                     </div>\r\n            </div>\r\n\r\n        </div>\r" +
"\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"DeviceAddDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:1000px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:5px 10px 5px 5px  !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearData()\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"EquipmentMasterFile\"");

WriteLiteral(">Equipment Master File</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(" style=\"margin:5px 0 8px 0;\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"EquipmentCode\"");

WriteLiteral(">Equipment Code</span>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DetailAddEquipmentCode\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral(" />\r\n                &nbsp;&nbsp;\r\n                <span");

WriteLiteral(" data-meaning=\"EquipmentName\"");

WriteLiteral(">Equipment Name</span>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DetailAddEquipmentName\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.SearchClick()\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" style=\"width:100%; height:100%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"display: inline-block;width: 45%; height:100%;margin:3px 5px;float:left;\"" +
"");

WriteLiteral(">\r\n                    <h6");

WriteLiteral(" class=\"m-title\"");

WriteLiteral(" data-meaning=\"Unused\"");

WriteLiteral(">Unused</h6>\r\n                    <div");

WriteLiteral(" id=\"table-bodydetail\"");

WriteLiteral(" style=\"margin:5px 8px; height:430px;\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" id=\"DeviceAddDialogTable\"");

WriteLiteral("></table>\r\n                    </div>\r\n                </div>\r\n                <d" +
"iv");

WriteLiteral(" style=\"float:left;display: inline-block;width: 4%;margin-top:16%;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"margin-bottom:20%;\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DeviceAddMoveRightClick();\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-triangle-right\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span></button>\r\n                    </div>\r\n                    <div>\r\n       " +
"                 <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DeviceAddMoveLeftClick();\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-triangle-left\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span></button>\r\n                    </div>\r\n                </div>\r\n          " +
"      <div");

WriteLiteral(" style=\"display: inline-block;width: 45%; height:100%;margin:3px 5px;float:left;\"" +
"");

WriteLiteral(">\r\n                    <h6");

WriteLiteral(" class=\"m-title\"");

WriteLiteral(" data-meaning=\"Used\"");

WriteLiteral(">Used</h6>\r\n                    <div");

WriteLiteral(" id=\"table-bodydetailone\"");

WriteLiteral(" style=\"margin:5px 8px; height:430px;\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" id=\"DeviceAddDialogChangeTable\"");

WriteLiteral("></table>\r\n                    </div>\r\n                </div>\r\n            </div>" +
"\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"padding: 5px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(" onclick=\"model.clearData()\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"DeviceAddSave\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(" onclick=\"model.DeviceAddClick()\"");

WriteLiteral(">Comfirm</button>\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"DetailAddDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:1000px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:5px 10px 5px 5px  !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearData()\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"MaintenanceItemsMasterFile\"");

WriteLiteral(">Maintenance Items Master File</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(" style=\"margin:5px 0 8px 0;\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"MaintenanceItems\"");

WriteLiteral(">Maintenance Item</span>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DetailAddMaintenanceItems\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral(" />\r\n                &nbsp;&nbsp;\r\n                <span");

WriteLiteral(" data-meaning=\"MaintenanceDescription\"");

WriteLiteral(">Maintenance Description</span>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DetailAddMaintenanceDescription\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DetailSearchClick()\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" style=\"width:100%; height:100%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"display: inline-block;width: 45%; height:100%;margin:3px 5px;float:left;\"" +
"");

WriteLiteral(">\r\n                    <h6");

WriteLiteral(" class=\"m-title\"");

WriteLiteral(" data-meaning=\"Unused\"");

WriteLiteral(">Unused</h6>\r\n                    <div");

WriteLiteral(" id=\"table-bodydetail\"");

WriteLiteral(" style=\"margin:5px 8px; height:430px;\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" id=\"DetailAddDialogTable\"");

WriteLiteral("></table>\r\n                    </div>\r\n                </div>\r\n                <d" +
"iv");

WriteLiteral(" style=\"float:left;display: inline-block;width: 4%;margin-top:16%;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"margin-bottom:20%;\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DetailAddMoveRightClick();\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-triangle-right\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span></button>\r\n                    </div>\r\n                    <div>\r\n       " +
"                 <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DetailAddMoveLeftClick();\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-triangle-left\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span></button>\r\n                    </div>\r\n                </div>\r\n          " +
"      <div");

WriteLiteral(" style=\"display: inline-block;width: 45%; height:100%;margin:3px 5px;float:left;\"" +
"");

WriteLiteral(">\r\n                    \r\n                    <h6");

WriteLiteral(" class=\"m-title\"");

WriteLiteral(" data-meaning=\"Used\"");

WriteLiteral(">used</h6>\r\n                    <div");

WriteLiteral(" id=\"table-bodydetailone\"");

WriteLiteral(" style=\"margin:5px 8px; height:430px;\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" id=\"DetailAddDialogChangeTable\"");

WriteLiteral("></table>\r\n                    </div>\r\n                </div>\r\n            </div>" +
"\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"padding: 5px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(" onclick=\"model.clearData()\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"DetailAddSave\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(" onclick=\"model.DetailAddClick()\"");

WriteLiteral(">Comfirm</button>\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"TypeDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Type\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"MaintenanceTypes\"");

WriteLiteral(">Maintenance Types</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"table-bodycode\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"TypeTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionTypeBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Type\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"commit\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Type\')\"");

WriteLiteral(" value=\"Comfirm\"");

WriteLiteral(">Commit</button>\r\n           </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral(@"
    <style>
        .mf-table-wrapper {
            overflow-x: auto;
        }

        .fix-table, .fix-head {
            width: 100%;
        }
        #DetailAddDialog .fix-table, #DetailAddDialog .fix-head {
                width: 120%;
            }
        #DeviceAddDialog .fix-table, #DeviceAddDialog .fix-head {
                width: 200%;
            }

        .m-title{
            text-align: center;
            font-size: 16px;
            font-weight: bold;
            margin: 0;
            padding: 0;
        }

    </style>
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 16745), Tuple.Create("\"", 16790)
, Tuple.Create(Tuple.Create("", 16751), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/knockout/knockout-3.0.0.js")
, 16751), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 16837), Tuple.Create("\"", 16877)
, Tuple.Create(Tuple.Create("", 16843), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/pagination.js")
, 16843), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 16924), Tuple.Create("\"", 16960)
, Tuple.Create(Tuple.Create("", 16930), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Rander.js")
, 16930), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17007), Tuple.Create("\"", 17044)
, Tuple.Create(Tuple.Create("", 17013), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Checker.js")
, 17013), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17091), Tuple.Create("\"", 17133)
, Tuple.Create(Tuple.Create("", 17097), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/FrozenColumn.js")
, 17097), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17180), Tuple.Create("\"", 17249)
, Tuple.Create(Tuple.Create("", 17186), Tuple.Create<System.Object, System.Int32>(Href("~/ViewModels/MES/EquipmentManagement/EMS00008MaintenanceList.js")
, 17186), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
