#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MonkeyFly.MES.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IntelligentParameters/INF00014.cshtml")]
    public partial class _Views_IntelligentParameters_INF00014_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_IntelligentParameters_INF00014_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\IntelligentParameters\INF00014.cshtml"
  
    ViewBag.Title = "INF00014";
    Layout = "~/Views/Shared/_LayoutLang.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tb_list\"");

WriteLiteral(" class=\"J-main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"J-toolbar\"");

WriteLiteral(">\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" data-meaning=\"CalendarCode\"");

WriteLiteral(">Calendar Code</span>\r\n        <input");

WriteLiteral(" id=\"Code\"");

WriteLiteral(" name=\"Code\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral("  autocomplete=\"off\"");

WriteLiteral("  />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-content\"");

WriteLiteral(" id=\"table-body\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"CalendarTable\"");

WriteLiteral(" data-toggle=\"true\"");

WriteLiteral(" data-mobile-responsive=\"true\"");

WriteLiteral("></table>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionBar\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"DuringMaintenanceDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"background: #fff !important; padding:15px 25px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:10px !important\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.DayCancel()\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</span>\r\n                    </button>\r\n                    <h6");

WriteLiteral(" id=\"inputTitle\"");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"DuringMaintenance\"");

WriteLiteral(">During Maintenance</h6>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row mf-layer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(" style=\"margin-bottom: 0px;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                    <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"CalendarCode\"");

WriteLiteral(">Calendar Code</span></td>\r\n                                        <td");

WriteLiteral(" Colspan=\"3\"");

WriteLiteral("><input");

WriteLiteral(" id=\"CalenderCode\"");

WriteLiteral(" maxlength=\"20\"");

WriteLiteral(" data-bind=\"value:Code\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:140px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"MainCalendar\"");

WriteLiteral(">MainCalendar</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"CalenderCode\"");

WriteLiteral(" maxlength=\"10\"");

WriteLiteral(" data-bind=\"value:Ifdefault\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:50px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled>\r\n                                            ");

WriteLiteral("\r\n                                        </td>\r\n                                " +
"        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"Status\"");

WriteLiteral(" style=\"margin:0px 5px 8px 4px; width:70px;\"");

WriteLiteral(">Status</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"CalenderCode\"");

WriteLiteral(" maxlength=\"10\"");

WriteLiteral(" data-bind=\"value:Status\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:50px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled>\r\n                                            ");

WriteLiteral("\r\n                                        </td>\r\n                                " +
"    </tr>\r\n                                    <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right;width:100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"CalendarDescription\"");

WriteLiteral(">Calendar Name</span></td>\r\n                                        <td");

WriteLiteral(" Colspan=\"7\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral("><input");

WriteLiteral(" id=\"CalendarName\"");

WriteLiteral(" maxlength=\"60\"");

WriteLiteral(" data-bind=\"value:Name\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 265px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled /></td>\r\n                                    </tr>\r\n                   " +
"                 <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right;width:100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Remark\"");

WriteLiteral(">Remark</span></td>\r\n                                        <td");

WriteLiteral(" Colspan=\"7\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral("><input");

WriteLiteral(" id=\"Comments\"");

WriteLiteral(" maxlength=\"120\"");

WriteLiteral(" data-bind=\"value:Comments\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 325px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled /></td>\r\n                                    </tr>\r\n                   " +
"                 <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:red;\"");

WriteLiteral(">*</span><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"StartYear\"");

WriteLiteral(">Start Year</span></td>\r\n                                        <td");

WriteLiteral(" Colspan=\"3\"");

WriteLiteral(" style=\"text-align:left\"");

WriteLiteral("><input");

WriteLiteral(" id=\"startDate\"");

WriteLiteral(" data-bind=\"value:startDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:130px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" readonly></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:red;\"");

WriteLiteral(">*</span><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"EndYear\"");

WriteLiteral(">End Year</span></td>\r\n                                        <td");

WriteLiteral(" Colspan=\"3\"");

WriteLiteral(" style=\"text-align:left\"");

WriteLiteral("><input");

WriteLiteral(" id=\"endDate\"");

WriteLiteral(" data-bind=\"value:endDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:130px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" readonly></td>\r\n                                    </tr>\r\n                     " +
"               <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Monday\"");

WriteLiteral(">Monday</span></td>\r\n                                        <td><input");

WriteLiteral(" id=\"MON\"");

WriteLiteral(" data-bind=\"value:MON\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" oninput=\"oninputnum(this)\"");

WriteLiteral(" maxLength=\"5\"");

WriteLiteral(" style=\"width:40px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral("></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Tuesday\"");

WriteLiteral(">Tuesday</span></td>\r\n                                        <td><input");

WriteLiteral(" id=\"TUE\"");

WriteLiteral(" data-bind=\"value:TUE\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" oninput=\"oninputnum(this)\"");

WriteLiteral(" maxLength=\"5\"");

WriteLiteral(" style=\"width:40px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral("></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Wednesday\"");

WriteLiteral(">Wednesday</span></td>\r\n                                        <td><input");

WriteLiteral(" id=\"WED\"");

WriteLiteral(" data-bind=\"value:WED\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" oninput=\"oninputnum(this)\"");

WriteLiteral(" maxLength=\"5\"");

WriteLiteral(" style=\"width:40px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral("></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Thursday\"");

WriteLiteral(">Thursday</span></td>\r\n                                        <td><input");

WriteLiteral(" id=\"THU\"");

WriteLiteral(" data-bind=\"value:THU\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" oninput=\"oninputnum(this)\"");

WriteLiteral(" maxLength=\"5\"");

WriteLiteral(" style=\"width:40px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral("></td>\r\n                                    </tr>\r\n                              " +
"      <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Friday\"");

WriteLiteral(">Friday</span></td>\r\n                                        <td><input");

WriteLiteral(" id=\"FRI\"");

WriteLiteral(" data-bind=\"value:FRI\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" oninput=\"oninputnum(this)\"");

WriteLiteral(" maxLength=\"5\"");

WriteLiteral(" style=\"width:40px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral("></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Saturday\"");

WriteLiteral(">Saturday</span></td>\r\n                                        <td><input");

WriteLiteral(" id=\"SAT\"");

WriteLiteral(" data-bind=\"value:SAT\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" oninput=\"oninputnum(this)\"");

WriteLiteral(" maxLength=\"5\"");

WriteLiteral(" style=\"width:40px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral("></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Sunday\"");

WriteLiteral(">Sunday</span></td>\r\n                                        <td><input");

WriteLiteral(" id=\"SUN\"");

WriteLiteral(" data-bind=\"value:SUN\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" oninput=\"oninputnum(this)\"");

WriteLiteral(" maxLength=\"5\"");

WriteLiteral(" style=\"width:40px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(@"></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </table>
                            </div>
                            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right; padding:15px 15px 0px 15px;\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(" onclick=\"model.DayCancel()\"");

WriteLiteral(" style=\"margin-bottom: 0px;\"");

WriteLiteral(">Cancel</button>\r\n                                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"DuringCommit\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(" onclick=\"model.duringSave()\"");

WriteLiteral(">Commit</button>                               \r\n                            </di" +
"v>\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"DetailsDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:580px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.DayCancel()\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"DayMaintenance\"");

WriteLiteral(">Day Maintenance</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(" style=\"margin-left:10px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                    <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"CalendarCode\"");

WriteLiteral(">Calendar Code</span></td>\r\n                        <td");

WriteLiteral(" Colspan=\"3\"");

WriteLiteral("><input");

WriteLiteral(" id=\"DCalendarCode\"");

WriteLiteral(" maxlength=\"20\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:140px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled></td>\r\n                        <td");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"margin:0px 5px 8px 10px;\"");

WriteLiteral(" data-meaning=\"MainCalendar\"");

WriteLiteral(">MainCalendar</span></td>\r\n                        <td");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"DMainCalendar\"");

WriteLiteral(" maxlength=\"10\"");

WriteLiteral(" data-bind=\"value:DMainCalendar\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:50px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled>\r\n                            ");

WriteLiteral("\r\n                        </td>\r\n                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"Status\"");

WriteLiteral(" style=\"margin:0px 5px 8px 10px; width:70px;\"");

WriteLiteral(">Status</span></td>\r\n                        <td");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"DStatus\"");

WriteLiteral(" maxlength=\"10\"");

WriteLiteral(" data-bind=\"value:DStatus\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:50px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled>\r\n                            ");

WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n                    <" +
"tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                        <td");

WriteLiteral(" style=\"text-align:right;width:100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"CalendarDescription\"");

WriteLiteral(">Calendar Name</span></td>\r\n                        <td");

WriteLiteral(" Colspan=\"7\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral("><input");

WriteLiteral(" id=\"DCalendarName\"");

WriteLiteral(" maxlength=\"60\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 265px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled /></td>\r\n                    </tr>\r\n                    <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                        <td");

WriteLiteral(" style=\"text-align:right;width:100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Remark\"");

WriteLiteral(">Remark</span></td>\r\n                        <td");

WriteLiteral(" Colspan=\"7\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral("><input");

WriteLiteral(" id=\"DRemark\"");

WriteLiteral(" maxlength=\"120\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 325px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" disabled /></td>\r\n                    </tr>\r\n                    <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                        <td");

WriteLiteral(" style=\"text-align:right\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Date\"");

WriteLiteral(">Date</span></td>\r\n                        <td");

WriteLiteral(" Colspan=\"7\"");

WriteLiteral(" style=\"text-align:left\"");

WriteLiteral(">\r\n                            <select");

WriteLiteral(" id=\"Date\"");

WriteLiteral(" data-bind=\"options:DateArray,optionsValue:\'value\',optionsText:\'text\',value:Date\"" +
"");

WriteLiteral(" style=\"width: 325px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral("></select>\r\n                        </td>\r\n                    </tr>\r\n           " +
"     </table>\r\n            </div>\r\n            <div");

WriteLiteral("  style=\"margin:5px 10px 5px 40px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"calSchedule\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" cellpadding=\"2\"");

WriteLiteral(" rules=\"all\"");

WriteLiteral(" title=\"日历\"");

WriteLiteral(" border=\"1\"");

WriteLiteral(" style=\"background-color: White; border-color: #FF950B; border-width: 1px; border" +
"-style: Solid; font-size: 9pt; width: 500px; border-collapse: collapse;\"");

WriteLiteral(">\r\n                    <tr");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n                        <th");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"td1\"");

WriteLiteral(" data-meaning=\"Sunday\"");

WriteLiteral(">Sunday</th>\r\n                        <th");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"td1\"");

WriteLiteral(" data-meaning=\"Monday\"");

WriteLiteral(">Monday</th>\r\n                        <th");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"td1\"");

WriteLiteral(" data-meaning=\"Tuesday\"");

WriteLiteral(">Tuesday</th>\r\n                        <th");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"td1\"");

WriteLiteral(" data-meaning=\"Wednesday\"");

WriteLiteral(">Wednesday</th>\r\n                        <th");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"td1\"");

WriteLiteral(" data-meaning=\"Thursday\"");

WriteLiteral(">Thursday</th>\r\n                        <th");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"td1\"");

WriteLiteral(" data-meaning=\"Friday\"");

WriteLiteral(">Friday</th>\r\n                        <th");

WriteLiteral(" align=\"center\"");

WriteLiteral(" valign=\"middle\"");

WriteLiteral(" scope=\"col\"");

WriteLiteral(" class=\"td1\"");

WriteLiteral(" data-meaning=\"Saturday\"");

WriteLiteral(">Saturday</th>\r\n                    </tr>\r\n                    <tr>\r\n            " +
"            <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td3\"");

WriteLiteral("></td>\r\n                        <td");

WriteLiteral(" align=\"left\"");

WriteLiteral(" valign=\"top\"");

WriteLiteral(" class=\"td2\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                </table>\r\n            </div>\r\n" +
"            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right; padding:10px 15px;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"Cancel\"");

WriteLiteral(" onclick=\"model.DayCancel()\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"DayComfirm\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(" onclick=\"model.DaySave()\"");

WriteLiteral(" value=\"Comfirm\"");

WriteLiteral(">Comfirm</button>                \r\n            </div>\r\n        </div>\r\n    </div>" +
"\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"inputDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <style>\r\n        .ui-state-highlight, .ui-widget-content .ui-state-highlig" +
"ht, .ui-widget-header .ui-state-highlight {\r\n            border: 1px solid red;\r" +
"\n        }\r\n    </style>\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:400px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" id=\"inputTitle\"");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"Import\"");

WriteLiteral(">Import</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"width:15%; display:inherit; float:left; margin-left:20px;\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"BtnBrowse\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" data-meaning=\"Browse\"");

WriteLiteral(">Browse</span>\r\n                        </button>\r\n                        <input" +
"");

WriteLiteral(" id=\"BtnFile\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" style=\"opacity:0\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" style=\"padding:5px; width:70%; display:inherit; float:left;\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" id=\"FileName\"");

WriteLiteral("></span>\r\n                    </div>\r\n                </div>\r\n            </div>\r" +
"\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-white\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" id=\"addFile\"");

WriteLiteral(" data-meaning=\"Save\"");

WriteLiteral(">Save</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <style>\r\n    .td1 {\r\n        color: #333333;\r\n        background-color: #DD" +
"E1EA;\r\n        border-color: #EBEBEB;\r\n        font-family: Tahoma;\r\n        fon" +
"t-size: 13px;\r\n        height: 30px;\r\n        text-align: center;\r\n        }\r\n\r\n" +
"    .td2 {\r\n        color: Red;\r\n        border-color: #EBEBEB;\r\n        border-" +
"width: 1px;\r\n        border-style: solid;\r\n        font-weight: bold;\r\n        h" +
"eight: 35px;\r\n        width: 14%;\r\n        text-align: center;\r\n        }\r\n\r\n   " +
" .td3 {\r\n        color: #333333;\r\n        border-color: #EBEBEB;\r\n        border" +
"-width: 1px;\r\n        border-style: solid;\r\n        font-weight: bold;\r\n        " +
"height: 35px;\r\n        width: 14%;\r\n        text-align: center;\r\n       }\r\n\r\n   " +
"     #table-body .mf-table-wrapper {\r\n            overflow-x: auto;\r\n        }\r\n" +
"\r\n        #table-body .fix-table, #table-body .fix-head {\r\n            width: 11" +
"6%;\r\n        }\r\n\r\n        /*.mf-layer {\r\n           box-sizing: content-box;\r\n  " +
"         height: 100%;\r\n        }\r\n\r\n\r\n        .mf-layer .ibox {\r\n            bo" +
"x-sizing: content-box;\r\n            height: calc(100% - 25px);\r\n            padd" +
"ing-right: 0px;\r\n        }\r\n\r\n        .mf-layer .ibox-content {\r\n            hei" +
"ght: calc(100% - 25px);\r\n            overflow-y: auto;\r\n        }*/\r\n\r\n        s" +
"elect {\r\n            height: 25.5px;\r\n            font-size: 12px;\r\n            " +
"color: #555;\r\n            background-color: #fff;\r\n            background-image:" +
" none;\r\n            border: 1px solid #ccc;\r\n            border-radius: 4px;\r\n  " +
"          -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);\r\n            box" +
"-shadow: inset 0 1px 1px rgba(0,0,0,.075);\r\n            -webkit-transition: bord" +
"er-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;\r\n            -o-t" +
"ransition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;\r\n         " +
"   transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;\r\n     " +
"       width:60px;\r\n        }\r\n    </style>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 21780), Tuple.Create("\"", 21825)
, Tuple.Create(Tuple.Create("", 21786), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/knockout/knockout-3.0.0.js")
, 21786), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 21872), Tuple.Create("\"", 21912)
, Tuple.Create(Tuple.Create("", 21878), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/pagination.js")
, 21878), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 21959), Tuple.Create("\"", 21995)
, Tuple.Create(Tuple.Create("", 21965), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Rander.js")
, 21965), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 22042), Tuple.Create("\"", 22079)
, Tuple.Create(Tuple.Create("", 22048), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Checker.js")
, 22048), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 22126), Tuple.Create("\"", 22182)
, Tuple.Create(Tuple.Create("", 22132), Tuple.Create<System.Object, System.Int32>(Href("~/ViewModels/MES/IntelligentParameters/INF00014.js")
, 22132), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
