#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MonkeyFly.MES.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IntelligentManufacturing/SFC00018.cshtml")]
    public partial class _Views_IntelligentManufacturing_SFC00018_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_IntelligentManufacturing_SFC00018_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\IntelligentManufacturing\SFC00018.cshtml"
  
    ViewBag.Title = "SFC00018";
    Layout = "~/Views/Shared/_LayoutLang.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tb_list\"");

WriteLiteral(" class=\"J-main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"J-toolbar\"");

WriteLiteral(">\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" data-meaning=\"StartOrderNumber\"");

WriteLiteral(" style=\"margin:0 5px;\"");

WriteLiteral(">Start Order Number</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"StartOrderNumber\"");

WriteLiteral(" style=\"width: 110px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-xs\"");

WriteLiteral(" onclick=\"model.MoCodeClick(\'#StartOrderNumber\')\"");

WriteLiteral(" style=\"margin-right:4px;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-desktop\"");

WriteLiteral("></span></button>\r\n        <span");

WriteLiteral(" data-meaning=\"EndOrderNumber\"");

WriteLiteral(" style=\"margin:0 5px;\"");

WriteLiteral(">End Order Number</span>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"EndOrderNumber\"");

WriteLiteral(" style=\"width: 110px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-xs\"");

WriteLiteral(" onclick=\"model.MoCodeClick(\'#EndOrderNumber\')\"");

WriteLiteral(" style=\"margin-right:4px;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-desktop\"");

WriteLiteral("></span></button>\r\n        <span");

WriteLiteral(" data-meaning=\"StartSingleDate\"");

WriteLiteral(" style=\"margin:0 5px;\"");

WriteLiteral(">Start Single Date</span>\r\n        <input");

WriteLiteral(" id=\"StartSingleDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input td_left\"");

WriteLiteral(" style=\"width:100px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n        <span");

WriteLiteral(" data-meaning=\"EndSingleDate\"");

WriteLiteral(" style=\"margin:0 5px;\"");

WriteLiteral(">End Single Date</span>\r\n        <input");

WriteLiteral(" id=\"EndSingleDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input td_left\"");

WriteLiteral(" style=\"width:100px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n        &nbsp;\r\n        <span");

WriteLiteral(" data-meaning=\"Status\"");

WriteLiteral(">Status</span>&nbsp;\r\n        <div");

WriteLiteral(" id=\"SStatus\"");

WriteLiteral(" data-bind=\"value:Status\"");

WriteLiteral(" style=\"display: inline-block; padding: 3px 5px; border:1px solid #ccc\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-content\"");

WriteLiteral(" id=\"table-body\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"SFC00018Table\"");

WriteLiteral(" data-toggle=\"true\"");

WriteLiteral(" data-mobile-responsive=\"true\"");

WriteLiteral("></table>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionBar\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"MoCodeDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:750px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\"font-size:20px\"");

WriteLiteral(" data-meaning=\"MoNoMasterFile\"");

WriteLiteral(">MoNoMasterFile</span>\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#MoNoTxt\', \'#GoodsNameTxt\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" data-meaning=\"MoNo\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px;\"");

WriteLiteral(">MoNo</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"MoNoTxt\"");

WriteLiteral(" style=\"width: 130px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <label");

WriteLiteral(" data-meaning=\"GoodsName\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px;\"");

WriteLiteral(">GoodsName</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"GoodsNameTxt\"");

WriteLiteral(" style=\"width: 130px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" onclick=\"model.searchMoCodeClick()\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"table-MoCode\"");

WriteLiteral(" style=\"margin:0px 10px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"MoCodeTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"MoCodePageBar\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;padding:5px 10px;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#MoNoTxt\', \'#GoodsNameTxt\')\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"MoCodeComfirm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(" onclick=\"model.clearInput(\'#MoNoTxt\', \'#GoodsNameTxt\')\"");

WriteLiteral(">Comfirm</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral(@"
    <style>
        .mf-table-wrapper {
            overflow-x: auto;
        }

        .fix-table, .fix-head {
            width: 100%;
        }

        #table-MoCode .fix-table, #table-MoCode .fix-head {
            width: 114%;
        }
    </style>
    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4254), Tuple.Create("\"", 4298)
, Tuple.Create(Tuple.Create("", 4261), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/plugins/iCheck/blue.css")
, 4261), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4332), Tuple.Create("\"", 4385)
, Tuple.Create(Tuple.Create("", 4338), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/hplus/plugins/iCheck/icheck.min.js")
, 4338), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4409), Tuple.Create("\"", 4454)
, Tuple.Create(Tuple.Create("", 4415), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/knockout/knockout-3.0.0.js")
, 4415), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4501), Tuple.Create("\"", 4582)
, Tuple.Create(Tuple.Create("", 4507), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js")
, 4507), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4606), Tuple.Create("\"", 4687)
, Tuple.Create(Tuple.Create("", 4612), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/bootstrap-datepicker/locales/bootstrap-datepicker.zh-TW.min.js")
, 4612), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4711), Tuple.Create("\"", 4751)
, Tuple.Create(Tuple.Create("", 4717), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/pagination.js")
, 4717), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4798), Tuple.Create("\"", 4834)
, Tuple.Create(Tuple.Create("", 4804), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Rander.js")
, 4804), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4881), Tuple.Create("\"", 4918)
, Tuple.Create(Tuple.Create("", 4887), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Checker.js")
, 4887), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4965), Tuple.Create("\"", 5024)
, Tuple.Create(Tuple.Create("", 4971), Tuple.Create<System.Object, System.Int32>(Href("~/ViewModels/MES/IntelligentManufacturing/SFC00018.js")
, 4971), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
