#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MonkeyFly.MES.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IntelligentManufacturing/SFC00021.cshtml")]
    public partial class _Views_IntelligentManufacturing_SFC00021_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_IntelligentManufacturing_SFC00021_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\IntelligentManufacturing\SFC00021.cshtml"
  
    ViewBag.Title = "SFC00021";
    Layout = "~/Views/Shared/_LayoutLang.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tb_list\"");

WriteLiteral(" class=\"J-main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"J-toolbar\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(" >\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                <lable");

WriteLiteral(" data-meaning=\"StartProcessNo\"");

WriteLiteral(">Start Process No</lable>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"StartProcessNo\"");

WriteLiteral(" style=\"width: 120px;\"");

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"StartProcessNoID\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-xs\"");

WriteLiteral(" onclick=\"model.StartProcessNo(\'#StartProcessNo\', \'#StartSequence\')\"");

WriteLiteral(" style=\"margin-right:4px;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-desktop\"");

WriteLiteral("></span></button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                <lable");

WriteLiteral(" data-meaning=\"EndProcessNo\"");

WriteLiteral(">End  Process No</lable>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"EndProcessNo\"");

WriteLiteral(" style=\"width: 120px;\"");

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"EndProcessNoID\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-xs\"");

WriteLiteral(" onclick=\"model.StartProcessNo(\'#EndProcessNo\', \'#EndSequence\')\"");

WriteLiteral(" style=\"margin-right:4px;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-desktop\"");

WriteLiteral("></span></button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                <lable");

WriteLiteral(" data-meaning=\"StartProcessDate\"");

WriteLiteral(" style=\"margin:0 5px;\"");

WriteLiteral(">Start Process Date</lable>\r\n                <input");

WriteLiteral(" id=\"SStartDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input td_left\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" style=\"width:100px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n                <lable");

WriteLiteral(" data-meaning=\"EndProcessDate\"");

WriteLiteral(" style=\"margin:0 5px;\"");

WriteLiteral(">End Process Date</lable>\r\n                <input");

WriteLiteral(" id=\"EStartDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input td_left\"");

WriteLiteral("readonly=\"readonly\"");

WriteLiteral(" style=\"width:100px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>             \r\n       </div>\r\n    <div");

WriteLiteral(" class=\"J-content\"");

WriteLiteral(" id=\"table-body\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"SFC00021Table\"");

WriteLiteral("></table>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionBar21\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"CodeDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:625px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.CleanClick()\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"WorkCenter\"");

WriteLiteral(">Work Center</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"ProcessNo\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px; width:60px;\"");

WriteLiteral(">Process No</span>\r\n                <input");

WriteLiteral(" id=\"ProcessNoSs\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 160px; margin:5px 5px 8px 0;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <span");

WriteLiteral(" data-meaning=\"ProcessDescription\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px; width:60px;\"");

WriteLiteral(">Process Description</span>\r\n                <input");

WriteLiteral(" id=\"ProcessDescription\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 160px; margin:5px 5px 8px 0;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DialogProcessSearch()\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"table-bodyMono\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"ProcessNoTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionMoNoBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral("  data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(" onclick=\"model.CleanClick()\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"ProcessCommit\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(" value=\"Comfirm\"");

WriteLiteral(">Commit</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n\r" +
"\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <style>\r\n        .mf-table-wrapper {\r\n            overflow-x: auto;\r\n      " +
"  }\r\n\r\n    </style>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4431), Tuple.Create("\"", 4475)
, Tuple.Create(Tuple.Create("", 4438), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/plugins/iCheck/blue.css")
, 4438), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4507), Tuple.Create("\"", 4570)
, Tuple.Create(Tuple.Create("", 4514), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/datetimepicker/bootstrap-datetimepicker.css")
, 4514), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4604), Tuple.Create("\"", 4657)
, Tuple.Create(Tuple.Create("", 4610), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/hplus/plugins/iCheck/icheck.min.js")
, 4610), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4681), Tuple.Create("\"", 4762)
, Tuple.Create(Tuple.Create("", 4687), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js")
, 4687), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4786), Tuple.Create("\"", 4867)
, Tuple.Create(Tuple.Create("", 4792), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/bootstrap-datepicker/locales/bootstrap-datepicker.zh-TW.min.js")
, 4792), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4891), Tuple.Create("\"", 4936)
, Tuple.Create(Tuple.Create("", 4897), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/knockout/knockout-3.0.0.js")
, 4897), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4983), Tuple.Create("\"", 5023)
, Tuple.Create(Tuple.Create("", 4989), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/pagination.js")
, 4989), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5070), Tuple.Create("\"", 5106)
, Tuple.Create(Tuple.Create("", 5076), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Rander.js")
, 5076), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5153), Tuple.Create("\"", 5190)
, Tuple.Create(Tuple.Create("", 5159), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Checker.js")
, 5159), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n \r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5240), Tuple.Create("\"", 5299)
, Tuple.Create(Tuple.Create("", 5246), Tuple.Create<System.Object, System.Int32>(Href("~/ViewModels/MES/IntelligentManufacturing/SFC00021.js")
, 5246), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
