#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MonkeyFly.MES.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IntelligentManufacturing/SFC00005Print.cshtml")]
    public partial class _Views_IntelligentManufacturing_SFC00005Print_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_IntelligentManufacturing_SFC00005Print_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\IntelligentManufacturing\SFC00005Print.cshtml"
  
    ViewBag.Title = "SFC00005Print";
    Layout = "~/Views/Shared/_LayoutLang.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tb_list\"");

WriteLiteral(" class=\"J-main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"J-toolbar\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"left\"");

WriteLiteral(" onclick=\"model.backClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-arrow-left\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</span></button>\r\n        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-toggle=\"tooltip\"");

WriteLiteral(" data-placement=\"left\"");

WriteLiteral(" onclick=\"model.printClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-add\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Print\"");

WriteLiteral(">Print</span></button>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-content\"");

WriteLiteral(">\r\n        <div>\r\n            <div");

WriteLiteral(" class=\"title1\"");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n                <h2");

WriteLiteral(" data-meaning=\"TaskCardPrint\"");

WriteLiteral(">Task Card Print</h2>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"items\"");

WriteLiteral(" style=\"text-align:center; margin-left:17px;\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"gridlist\"");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(" style=\"width: 100%; height: 100%; text-align:center; margin: 5px 45px 5px 30px;\"" +
"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" id=\"TaskCardPrint\"");

WriteLiteral(" style=\"border:2px solid black; border-bottom:none;\"");

WriteLiteral(">\r\n                <tr>\r\n                    <td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"MoNo\"");

WriteLiteral(">Mo No.</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"MoNo\"");

WriteLiteral("></span></td>\r\n                    <td");

WriteLiteral(" colspan=\"4\"");

WriteLiteral(" rowspan=\"11\"");

WriteLiteral(" style=\"width:540px;\"");

WriteLiteral(">3</td>\r\n                </tr>\r\n                <tr>\r\n                    <td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"ItemNo\"");

WriteLiteral(">Item No.</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"ItemNo\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"GoodsName\"");

WriteLiteral(">Goods Name</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"GoodsName\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"DispatchAmount\"");

WriteLiteral(">Dispatch Amount</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"DispatchAmount\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"WorkCenter\"");

WriteLiteral(" style=\"font-weight:800;\"");

WriteLiteral(">Work Center</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"WorkCenter\"");

WriteLiteral(" style=\"font-weight:800;\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"ManufacturingProcess\"");

WriteLiteral(" style=\"font-weight:800;\"");

WriteLiteral(">Manufacture Process</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"ManufacturingProcess\"");

WriteLiteral(" style=\"font-weight:800;\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"Process\"");

WriteLiteral(" style=\"font-weight:800;\"");

WriteLiteral(">Process</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"Process\"");

WriteLiteral(" style=\"font-weight:800;\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"UnderWorkCenter\"");

WriteLiteral(">Under Work Center</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"UnderWorkCenter\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"UnderCreateProcess\"");

WriteLiteral(">Under Create Process</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"UnderCreateProcess\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"UnderProcess\"");

WriteLiteral(">Under Process</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"UnderProcess\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"OrderNo\"");

WriteLiteral(">Order No.</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"OrderNo\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n                <tr>\r\n                    <" +
"td");

WriteLiteral(" style=\"width:150px; border-bottom:none;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"Client\"");

WriteLiteral(">Client</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px; border-bottom:none;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"Client\"");

WriteLiteral("></span></td>\r\n                    <td");

WriteLiteral(" style=\"width:100px; border-bottom:none;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"FinishNo\"");

WriteLiteral(">Finish No.</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:170px; border-bottom:none;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"FinishNo\"");

WriteLiteral("></span></td>\r\n                    <td");

WriteLiteral(" style=\"width:100px; border-bottom:none;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"FinProQty\"");

WriteLiteral(">FinPro Qty.</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:170px; border-bottom:none;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"FinProQty\"");

WriteLiteral("></span></td>\r\n                </tr>\r\n            </table>\r\n            <table");

WriteLiteral(" id=\"Equipmentable\"");

WriteLiteral(" style=\"border:2px solid black; border-top:none;\"");

WriteLiteral(">\r\n                <tr>\r\n                    <td");

WriteLiteral(" style=\"width:130px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"SourceClass\"");

WriteLiteral(">Source Class</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:170px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"EquipmentCode\"");

WriteLiteral(">Equipment Code</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:430px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"EquipmentDescription\"");

WriteLiteral(">Equipment Dept.</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:170px; border-right:2px solid black;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"MainResource\"");

WriteLiteral(">Main Resource</span></td>\r\n                </tr>\r\n                ");

WriteLiteral("\r\n            </table>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral(@"
    <style>
        #TaskCardPrint {
            table-layout: fixed;
        }

        #Equipmentable {
            table-layout: fixed;
        }

        #TaskCardPrint tr {
            line-height: 29px;
        }

        #TaskCardPrint td {
            border: 1px solid black;
            word-break: break-word;
        }

        #Equipmentable tr {
            line-height: 29px;
        }

        #Equipmentable td {
            border: 1px solid black;
            word-break: break-word;
        }

        .title3 {
            text-align: center;
            display: inline-block;
            width: 24%;
        }
    </style>
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6195), Tuple.Create("\"", 6240)
, Tuple.Create(Tuple.Create("", 6201), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/knockout/knockout-3.0.0.js")
, 6201), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6287), Tuple.Create("\"", 6327)
, Tuple.Create(Tuple.Create("", 6293), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/pagination.js")
, 6293), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6374), Tuple.Create("\"", 6410)
, Tuple.Create(Tuple.Create("", 6380), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Rander.js")
, 6380), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6457), Tuple.Create("\"", 6494)
, Tuple.Create(Tuple.Create("", 6463), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Checker.js")
, 6463), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6541), Tuple.Create("\"", 6605)
, Tuple.Create(Tuple.Create("", 6547), Tuple.Create<System.Object, System.Int32>(Href("~/ViewModels/MES/IntelligentManufacturing/SFC00005Print.js")
, 6547), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
