#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MonkeyFly.MES.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IntelligentManufacturing/SFC00008.cshtml")]
    public partial class _Views_IntelligentManufacturing_SFC00008_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_IntelligentManufacturing_SFC00008_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\IntelligentManufacturing\SFC00008.cshtml"
  
    ViewBag.Title = "SFC00008 完工调整作业";
    Layout = "~/Views/Shared/_LayoutLang.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!--<h2>SFC00008</h2>-->\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"tb_list\"");

WriteLiteral(" id=\"J-main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"J-toolbar\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n        ");

WriteLiteral("\r\n        &nbsp;\r\n        <span");

WriteLiteral(" data-meaning=\"CompletedNo\"");

WriteLiteral(">AdjustmentNo</span>\r\n        &nbsp;\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" style=\"width: 160px;\"");

WriteLiteral(" data-bind=\"value: CompletedNo\"");

WriteLiteral(" id=\"InspectionCode\"");

WriteLiteral(" />\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-content\"");

WriteLiteral(" id=\"table-body\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"AdjustmentTable\"");

WriteLiteral("></table>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginationBar\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"AddDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:880px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"background: #fff !important;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:10px !important\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.ClearAddValue();\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" onclick=\"model.ClearAddValue();\"");

WriteLiteral(">Cancel</span>\r\n                    </button>\r\n                    <h6");

WriteLiteral(" id=\"inputTitle\"");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"CompletedAdjustment\"");

WriteLiteral(">Add Completed Adjustment</h6>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row mf-layer\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(" style=\"margin-bottom: 0px;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(" id=\"addTable\"");

WriteLiteral(">\r\n                                    <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:red;\"");

WriteLiteral(">*</span><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"AdjustmentNoSelect\"");

WriteLiteral(">Adjustment No</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:170px;\"");

WriteLiteral("> <select");

WriteLiteral(" class=\"search-select\"");

WriteLiteral("  style=\"text-align:left; width: 170px !important;\"");

WriteLiteral("  autocomplete=\"off\"");

WriteLiteral("  id=\"AutoType\"");

WriteLiteral(" data-bind=\"options: typeData, optionsText: \'text\', optionsValue: \'value\',event: " +
"{click: getAutoNum},value:AddCompletedNo \"");

WriteLiteral("  ></select> </td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:red;\"");

WriteLiteral(">*</span><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"CompletedNo\"");

WriteLiteral(">Completed No</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" id=\"AddCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral("  disabled");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral("></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:red;\"");

WriteLiteral(">*</span><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"DocDate\"");

WriteLiteral(">Document Date</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"AddDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" onchange=\"model.getAutoNum()\"");

WriteLiteral("  readonly=\"readonly\"");

WriteLiteral(">\r\n                                        </td>\r\n                              \r" +
"\n                                    </tr>                     \r\n               " +
"                     <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"width:100px; text-align:right;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"color:red;\"");

WriteLiteral(">*</span><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"OldCompletedNo\"");

WriteLiteral(">OldCompletedNo</span> </td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:139px;\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"AddOldComId\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"AddOldComCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:140px;\"");

WriteLiteral(" disabled>\r\n                                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"AddOldComCodebtn\"");

WriteLiteral(" class=\"btn btn-success btn-xs\"");

WriteLiteral(" onclick=\"model.SearchOldCompletedNo()\"");

WriteLiteral(" style=\"margin-right:4px;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-desktop\"");

WriteLiteral("></span></button>\r\n                                        </td>\r\n               " +
"                         <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"TaskNo\"");

WriteLiteral(">Task No </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addTaskNo\"");

WriteLiteral("/></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"WorkOrderNum\"");

WriteLiteral(">Work Order Number </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addWorkOrderNum\"");

WriteLiteral("/></td>\r\n                                       </tr>\r\n                          " +
"          <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Part\"");

WriteLiteral(">Part No </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addPart\"");

WriteLiteral(" /></td>\r\n\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"ItemDescription\"");

WriteLiteral(">Item Description</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addItemDescription\"");

WriteLiteral("/></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"ItemSpecification\"");

WriteLiteral(">Item Specification </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addItemSpecification\"");

WriteLiteral("/></td>\r\n                                        \r\n                              " +
"       </tr>\r\n                                    <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"ManufacturingUnit\"");

WriteLiteral(">Manufacturing Unit</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addManufacturingUnit\"");

WriteLiteral(" /></td>\r\n\r\n                                       <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"AuxiliaryUnit\"");

WriteLiteral(">AuxiliaryUnit </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addAuxiliaryUnit\"");

WriteLiteral("/></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"UnitRate\"");

WriteLiteral(">Unit Rate </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addUnitRate\"");

WriteLiteral("/></td>\r\n                                        \r\n                              " +
"      </tr>\r\n                            \r\n                                    <" +
"tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"FinishQty\"");

WriteLiteral(">Finish Quantity </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" maxlength=\"16\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" id=\"addFinishQty\"");

WriteLiteral(" /></td>\r\n\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"ScrappedQty\"");

WriteLiteral(">Scrapped Quantity </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral("   maxlength=\"16\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral("  value=\"0\"");

WriteLiteral("  id=\"addScrappedQty\"");

WriteLiteral("/></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"DifferenceQty\"");

WriteLiteral(">Difference Quantity </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral("   maxlength=\"16\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral("  value=\"0\"");

WriteLiteral("  id=\"addDifferenceQty\"");

WriteLiteral("/></td>\r\n                                       \r\n                               " +
"     </tr>\r\n                                    <tr");

WriteLiteral(" style=\"height:40px\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"RepairQty\"");

WriteLiteral(">Repaired Quantity </span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" maxlength=\"16\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" id=\"addRepairQty\"");

WriteLiteral(" /></td>\r\n\r\n                                         <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"ValidLaborHour\"");

WriteLiteral(">ValidLabor Hour</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" maxlength=\"16\"");

WriteLiteral(" onblur=\"model.isValidHour(this)\"");

WriteLiteral("  value=\"00:00:00\"");

WriteLiteral("  class=\"search-input\"");

WriteLiteral(" id=\"addValidLaborHour\"");

WriteLiteral("  /></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align: right; width: 100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"text-align: center; width: 100px; padding-right:5px\"");

WriteLiteral(" data-meaning=\"InvalidLaborHour\"");

WriteLiteral(">InvalidLabor Hour</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" maxlength=\"16\"");

WriteLiteral(" onblur=\"model.isValidHour(this)\"");

WriteLiteral("  value=\"00:00:00\"");

WriteLiteral("  class=\"search-input\"");

WriteLiteral(" id=\"addInvalidLaborHour\"");

WriteLiteral("  /></td>\r\n                                       \r\n                             " +
"       </tr>\r\n                             \r\n                                   " +
" <tr");

WriteLiteral(" style=\"height:40px;\"");

WriteLiteral(">\r\n                                        <td");

WriteLiteral(" style=\"text-align: right; width: 100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"ValidMachineHour\"");

WriteLiteral(">ValidMachine Hour</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" maxlength=\"16\"");

WriteLiteral(" onblur=\"model.isValidHour(this)\"");

WriteLiteral(" value=\"00:00:00\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" id=\"addValidMachine\"");

WriteLiteral(" /></td>\r\n\r\n                                        <td");

WriteLiteral(" style=\"text-align: right; width: 100px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"InvalidMachineHour\"");

WriteLiteral(">InvalidMachine  Hour</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left; width:153px;\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" maxlength=\"16\"");

WriteLiteral(" onblur=\"model.isValidHour(this)\"");

WriteLiteral("  value=\"00:00:00\"");

WriteLiteral("  class=\"search-input\"");

WriteLiteral(" id=\"addInvalidMachine\"");

WriteLiteral(" onclick=\"model.judgeNum(this)\"");

WriteLiteral("/></td>                      \r\n                                        <td");

WriteLiteral(" style=\"text-align:right; width:80px;\"");

WriteLiteral("><span");

WriteLiteral(" style=\"padding-right:5px\"");

WriteLiteral(" data-meaning=\"Remark\"");

WriteLiteral(">Remark</span></td>\r\n                                        <td");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral("  maxlength=\"120\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width:170px;\"");

WriteLiteral(" id=\"addRemark\"");

WriteLiteral("/></td>\r\n\r\n                                     </tr>\r\n\r\n                        " +
"          \r\n                                </table>\r\n                          " +
"  </div>\r\n                            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" style=\"margin-bottom:0px;\"");

WriteLiteral(" onclick=\"model.ClearAddValue();\"");

WriteLiteral(">Cancel</button>\r\n                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"AddCode\"");

WriteLiteral(" onclick=\"model.AddSaveClick()\"");

WriteLiteral(" data-meaning=\"Save\"");

WriteLiteral(">Save</button>\r\n                            </div>\r\n                        </div" +
">\r\n                    </div>\r\n                </div>\r\n            </div>\r\n     " +
"   </div>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"OldCompletedNoDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <style>\r\n        .ui-state-highlight, .ui-widget-content .ui-state-highlig" +
"ht, .ui-widget-header .ui-state-highlight {\r\n            border: 1px solid red;\r" +
"\n        }\r\n    </style>\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:800px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <span");

WriteLiteral("  class=\"modal-title\"");

WriteLiteral("  data-meaning=\"OldCompletedNo\"");

WriteLiteral(">OldCompletedNo</span>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#OldCompletedNoInput\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" style=\"font-size:12px;margin: 0 7px;\"");

WriteLiteral(" data-meaning=\"OldCompletedNo\"");

WriteLiteral(">\r\n                    OldCompleted No\r\n                </span>\r\n         \r\n     " +
"           <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OldCompletedNoInput\"");

WriteLiteral(" data-bind=\"value: OldCompletedNo\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 130px; margin:5px 5px 8px 0;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.OldCompNoSearch()\"");

WriteLiteral(" id=\"Find\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"OldCompletedNo\"");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"OldCompletedNoTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"pagiOldCompletedNoBar\"");

WriteLiteral(" style=\"padding-bottom:5px!important\"");

WriteLiteral("></div>\r\n\r\n            <div");

WriteLiteral(" style=\"text-align:right;padding:5px 10px;\"");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#OldCompletedNoInput\')\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"OldCompletedNoConfirmBtn\"");

WriteLiteral("  data-meaning=\"Confirm\"");

WriteLiteral(">Confirm</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ImportDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <style>\r\n        .ui-state-highlight, .ui-widget-content .ui-state-highlig" +
"ht, .ui-widget-header .ui-state-highlight {\r\n            border: 1px solid red;\r" +
"\n        }\r\n    </style>\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:400px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <span");

WriteLiteral("  class=\"modal-title\"");

WriteLiteral("  data-meaning=\"Import\"");

WriteLiteral(">Import</span>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div>\r\n                    <div>\r\n                        <but" +
"ton");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"BtnBrowse\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" data-meaning=\"Browse\"");

WriteLiteral(">Browse</span>\r\n                        </button>\r\n                        <input" +
"");

WriteLiteral(" id=\"BtnFile\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" accept=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\"");

WriteLiteral(" style=\"opacity:0;position: absolute; top: 25px;\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" style=\"padding:5px;\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" id=\"FileName\"");

WriteLiteral("></span>\r\n                    </div>\r\n                </div>\r\n            </div>\r" +
"\n            <div");

WriteLiteral(" style=\"text-align:right;padding:5px 10px;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"BtnImport\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(">Confirm</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"resourceReportDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:641px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding: 16px !important;\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"ResourceReporting\"");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" >\r\n                    Resource Report\r\n                </span>\r\n               " +
" <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" onclick=\"model.CancelResourceReportingClick()\"");

WriteLiteral(" >\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" id=\"resourceContent\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"resourceReportTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionRReportBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("  onclick=\"model.CancelResourceReportingClick()\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" id=\"CallAdd\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Add\"");

WriteLiteral(" onclick=\"model.AddRReportClick()\"");

WriteLiteral(" value=\"Add\"");

WriteLiteral(">Add</button>\r\n                <button");

WriteLiteral(" id=\"CallChange\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Change\"");

WriteLiteral(" onclick=\"model.ChangeRReportClick()\"");

WriteLiteral(" value=\"Change\"");

WriteLiteral(">Change</button>\r\n                <button");

WriteLiteral(" id=\"CallDeletion\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Deletion\"");

WriteLiteral(" onclick=\"model.DeleteRReportClick()\"");

WriteLiteral(" value=\"Deletion\"");

WriteLiteral(">Deletion</button>              \r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.ConfirmRReportClick()\"");

WriteLiteral(">Confirm</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ResourceDataDialog\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:550px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:5px 10px 5px 5px  !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#SourceCodeID\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <span");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral("  data-meaning=\"SourceCode\"");

WriteLiteral(">Source Code</span>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"EquipmentOrMan\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px; width:60px;\"");

WriteLiteral(">EquipmentOrMan</span>\r\n                <select");

WriteLiteral(" class=\"search-select\"");

WriteLiteral(" id=\"SelectResourceType\"");

WriteLiteral(" style=\"width: 100px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" value=\"L\"");

WriteLiteral(" data-meaning=\"Man\"");

WriteLiteral(">Man</option>\r\n                    <option");

WriteLiteral(" value=\"M\"");

WriteLiteral(" data-meaning=\"Equipment\"");

WriteLiteral(">Equipment</option>\r\n                </select>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DialogEquipmentOrManSearch()\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"padding: 0px 5px 2px!important;background-color:#fff;\"");

WriteLiteral(">\r\n                \r\n                <table");

WriteLiteral(" id=\"ResourceDataTable\"");

WriteLiteral(" data-toggle=\"true\"");

WriteLiteral(" data-mobile-responsive=\"true\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"paginagionResourceDataBar\"");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" style=\"padding-bottom:5px!important\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"padding: 5px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#SourceCodeID\')\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"ResourceDataComfirm\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(">Confirm</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ExceptionDescriptionDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:650px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding: 16px !important\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"ExceptionDescription\"");

WriteLiteral("  class=\"modal-title\"");

WriteLiteral(" >\r\n                    Exception Description\r\n                </span>\r\n         " +
"       <button");

WriteLiteral(" class=\"close\"");

WriteLiteral("  onclick=\"model.CancelUnusualQtyClick()\"");

WriteLiteral(" >\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"InvalidHourContent\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"ExceptionDescriptionTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"pagiExceptionDesBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(" id=\"opr_btns\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("  data-meaning=\"Cancel\"");

WriteLiteral(" onclick=\"model.CancelUnusualQtyClick()\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" id=\"UnusualQtyAdd\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Add\"");

WriteLiteral(" onclick=\"model.AddExcDesClick()\"");

WriteLiteral(" value=\"Add\"");

WriteLiteral(">Add</button>\r\n                <button");

WriteLiteral(" id=\"UnusualQtyChange\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Change\"");

WriteLiteral(" onclick=\"model.ChangeExcDesClick()\"");

WriteLiteral(" value=\"Change\"");

WriteLiteral(">Change</button>\r\n                <button");

WriteLiteral(" id=\"UnusualQtyDeletion\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Deletion\"");

WriteLiteral(" onclick=\"model.DeleteExcDesClick()\"");

WriteLiteral(" value=\"Deletion\"");

WriteLiteral(">Deletion</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"UnusualQtyComfirm\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.ConfirmExcDesClick()\"");

WriteLiteral(">Confirm</button>\r\n                \r\n            </div>\r\n        </div>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"InvalidHourDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:700px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding: 16px; !important\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"InvalidHour\"");

WriteLiteral("  class=\"modal-title\"");

WriteLiteral(" >\r\n                    Invalid Hour\r\n                </span>\r\n                <b" +
"utton");

WriteLiteral(" class=\"close\"");

WriteLiteral("  onclick=\"model.CancelInvHClick()\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"InvalidHourContent\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"InvalidHourTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"pagiInvalidHourBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral("  data-meaning=\"Cancel\"");

WriteLiteral(" onclick=\"model.CancelInvHClick()\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" id=\"InvalidHourAdd\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Add\"");

WriteLiteral(" onclick=\"model.AddInvHClick()\"");

WriteLiteral(" value=\"Add\"");

WriteLiteral(">Add</button>\r\n                <button");

WriteLiteral(" id=\"InvalidHourlChange\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Change\"");

WriteLiteral(" onclick=\"model.ChangeInvHClick()\"");

WriteLiteral(" value=\"Change\"");

WriteLiteral(">Change</button>\r\n                <button");

WriteLiteral(" id=\"InvalidHourDeletion\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Deletion\"");

WriteLiteral(" onclick=\"model.DeleteInvHClick()\"");

WriteLiteral(" value=\"Deletion\"");

WriteLiteral(">Deletion</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"InvalidHCommit\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.ConfirmInvHClick()\"");

WriteLiteral(">Confirm</button>\r\n                \r\n            </div>\r\n        </div>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"BatchAttributeDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:890px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding: 16px; !important\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"BatchAttribute\"");

WriteLiteral("  class=\"modal-title\"");

WriteLiteral(" >\r\n                    BatchAttribute\r\n                </span>\r\n                " +
"<button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"BatchAttributeContent\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"BatchAttributeTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"pagiBatchAttrBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" onclick=\"model.CancelEv(\'#BatchAttributeDialog\')\"");

WriteLiteral(">Cancel</button>\r\n                ");

WriteLiteral("\r\n              \r\n                <button");

WriteLiteral(" id=\"CallChange\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Change\"");

WriteLiteral(" onclick=\"model.ChangeBatchAttrClick()\"");

WriteLiteral(" value=\"Change\"");

WriteLiteral(">Change</button>\r\n                ");

WriteLiteral("\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"CallCommit\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.ConfirmBatchAttrClick()\"");

WriteLiteral(">Confirm</button>\r\n                \r\n            </div>\r\n        </div>\r\n    </di" +
"v>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ItemPropertyDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:800px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding: 16px; !important\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"DataValue\"");

WriteLiteral("  class=\"modal-title\"");

WriteLiteral(" >\r\n                    Item Property\r\n                </span>\r\n                <" +
"button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"ItemPropertyContent\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"ItemPropertyTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"pagiItemPropertyBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n               <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-meaning=\"Change\"");

WriteLiteral(" onclick=\"model.ChangeItemPropertyClick()\"");

WriteLiteral(" value=\"Change\"");

WriteLiteral(">Change</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"ItemPropertyCommit\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.ConfirmItemPropertyClick()\"");

WriteLiteral(">Confirm</button>\r\n               \r\n            </div>\r\n        </div>\r\n    </div" +
">\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ReasonCodeDialog1\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#ReasonCode1\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"ReasonFile\"");

WriteLiteral(">Reason Code File</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"ReasonFile\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px; width:60px;\"");

WriteLiteral(">Reason  Code</span>\r\n                <input");

WriteLiteral(" id=\"ReasonCode1\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 160px; margin:5px 5px 8px 0;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.ReasonCodeSearch1()\"");

WriteLiteral(" id=\"Find\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"ReasonTable1\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionReasonBar1\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#ReasonCode1\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"ReasonCodeCommit1\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.clearInput(\'#ReasonCode1\')\"");

WriteLiteral(" value=\"Confirm\"");

WriteLiteral(">Commit</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ReasonCodeDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#InputReasonCode\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"ReasonFile\"");

WriteLiteral(">Reason Code File</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"ReasonFile\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px; width:60px;\"");

WriteLiteral(">Reason  Code</span>\r\n                <input");

WriteLiteral(" id=\"InputReasonCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 160px; margin:5px 5px 8px 0;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.ReasonCodeSearch()\"");

WriteLiteral(" id=\"Find\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"table-bodyReasonCode\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"ReasonTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionReasonBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#InputReasonCode\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"ReasonCodeCommit\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.clearInput(\'#InputReasonCode\')\"");

WriteLiteral(" value=\"Confirm\"");

WriteLiteral(">Commit</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"GroupDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:680px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#ReasonGroupCode\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"GroupFile\"");

WriteLiteral(">Reason Group Code File</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"ReasonGroupCode\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px; width:60px;\"");

WriteLiteral(">Reason Group Code</span>\r\n                <input");

WriteLiteral(" id=\"ReasonGroupCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 160px; margin:5px 5px 8px 0;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.GroupSearch()\"");

WriteLiteral(" id=\"Find\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"table-bodyGroup\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"GroupTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionGroupBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#ReasonGroupCode\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"GroupCommit\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.clearInput(\'#ReasonGroupCode\')\"");

WriteLiteral(" value=\"Confirm\"");

WriteLiteral(">Commit</button>\r\n                \r\n            </div>\r\n        </div>\r\n    </div" +
">\r\n</div>\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"DatavalueDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Datavalue\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"DataValue\"");

WriteLiteral(">Item Property</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"ItemProperty\"");

WriteLiteral(" style=\"margin:5px 5px 8px 10px; width:60px;\"");

WriteLiteral(">Item Property</span>\r\n                <input");

WriteLiteral(" id=\"Datavalue\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 160px; margin:5px 5px 8px 0;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.DatavalueSearch()\"");

WriteLiteral(" id=\"Find\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"table-bodyDatavalue\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"DatavalueTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"pagiDatavalueBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Datavalue\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"DataValueCommit\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Datavalue\')\"");

WriteLiteral(" value=\"Confirm\"");

WriteLiteral(">Commit</button>\r\n                \r\n            </div>\r\n        </div>\r\n    </div" +
">\r\n</div>\r\n\r\n\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"importDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <style>\r\n        .ui-state-highlight, .ui-widget-content .ui-state-highlig" +
"ht, .ui-widget-header .ui-state-highlight {\r\n            border: 1px solid red;\r" +
"\n        }\r\n    </style>\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width: 400px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" style=\"padding: 16px !important\"");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <span");

WriteLiteral("  class=\"modal-title\"");

WriteLiteral("  data-meaning=\"Import\"");

WriteLiteral(">\r\n                    Import\r\n                </span>\r\n                <button");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"close\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</span>\r\n                </button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div>\r\n                    <div>\r\n                        <but" +
"ton");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" id=\"Browse\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" data-meaning=\"Browse\"");

WriteLiteral(">Browse</span>\r\n                        </button>\r\n                        <input" +
"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" style=\"opacity: 0;\"");

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" style=\"padding: 5px;\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" id=\"FileName\"");

WriteLiteral("></span>\r\n                    </div>\r\n                </div>\r\n            </div>\r" +
"\n            <div");

WriteLiteral(" style=\"text-align:right; padding:5px 10px;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" data-meaning=\"Confirm\"");

WriteLiteral(" id=\"BtnImport\"");

WriteLiteral(">\r\n                    Confirm\r\n                </button>\r\n            </div>\r\n  " +
"      </div>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n");

DefineSection("scripts", () => {

            
            #line 531 "..\..\Views\IntelligentManufacturing\SFC00008.cshtml"
  
            
            #line default
            #line hidden
WriteLiteral(@"
<style>


      #AddOldComCodebtn{
          margin-bottom:0 !important;
          margin-right:0 !important;
      }

    .mf-table-wrapper {
        overflow-x: auto;
    }

    #table-body .fix-table, #table-body .fix-head {
        width: 322%;
    }

    #resourceContent .fix-table, #resourceContent .fix-head {
        width: 100%;
    }

    #OldCompletedNo .fix-table, #OldCompletedNo .fix-head {
        width: 160%;
    }

    #InvalidHourContent .fix-table, #InvalidHourContent .fix-head{
        width: 100%;
    }
</style>

<script");

WriteAttribute("src", Tuple.Create(" src=\"", 37398), Tuple.Create("\"", 37443)
, Tuple.Create(Tuple.Create("", 37404), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/knockout/knockout-3.0.0.js")
, 37404), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 37486), Tuple.Create("\"", 37526)
, Tuple.Create(Tuple.Create("", 37492), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/pagination.js")
, 37492), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 37569), Tuple.Create("\"", 37605)
, Tuple.Create(Tuple.Create("", 37575), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Rander.js")
, 37575), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 37648), Tuple.Create("\"", 37685)
, Tuple.Create(Tuple.Create("", 37654), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Checker.js")
, 37654), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 37728), Tuple.Create("\"", 37787)
, Tuple.Create(Tuple.Create("", 37734), Tuple.Create<System.Object, System.Int32>(Href("~/ViewModels/MES/IntelligentManufacturing/SFC00008.js")
, 37734), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n                                    ");

});

        }
    }
}
#pragma warning restore 1591
