#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MonkeyFly.MES.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IntelligentCouplet/IOT00002Machine.cshtml")]
    public partial class _Views_IntelligentCouplet_IOT00002Machine_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_IntelligentCouplet_IOT00002Machine_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\IntelligentCouplet\IOT00002Machine.cshtml"
  
    ViewBag.Title = "IOT00002Machine";
    Layout = "~/Views/Shared/_LayoutLang.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tb_list\"");

WriteLiteral(" class=\"J-main\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"J-toolbar\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" onclick=\"model.backClick()\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa icon-arrow-left\"");

WriteLiteral("></i> <span");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(">取消</span></button>\r\n        ");

WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" data-meaning=\"EquipmentCode\"");

WriteLiteral(">EquipmentCode</span>\r\n        <input");

WriteLiteral(" id=\"EquipmentCode\"");

WriteLiteral(" name=\"EquipmentCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 140px;\"");

WriteLiteral(" disabled");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-xs\"");

WriteLiteral(" onclick=\"model.SearchCode(\'#EquipmentCode\')\"");

WriteLiteral(" style=\"margin-right:4px;\"");

WriteLiteral("><span");

WriteLiteral(" class=\"fa fa-desktop\"");

WriteLiteral("></span></button>\r\n        <span");

WriteLiteral(" data-meaning=\"EquipmentDescription\"");

WriteLiteral(" style=\"margin-left:20px;\"");

WriteLiteral(">Equipment Description</span>\r\n        <input");

WriteLiteral(" id=\"EquipmentDescription\"");

WriteLiteral(" name=\"EquipmentDescription\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 140px;\"");

WriteLiteral(" disabled />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"J-content\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" id=\"gridlist\"");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(" style=\"width: 100%; height: 100%; text-align:center; margin: 5px 10px 5px 10px;\"" +
"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"topTab\"");

WriteLiteral(">\r\n                <tr");

WriteLiteral(" class=\"topTaTr\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px; text-align:left\"");

WriteLiteral("></td>\r\n                    <td");

WriteLiteral(" rowspan=\"7\"");

WriteLiteral(" style=\"width:540px;\"");

WriteLiteral("><img");

WriteLiteral(" id=\"EquipmentImgUrl\"");

WriteLiteral(" src=\"about:blank\"");

WriteLiteral(" style=\"width:537px;height:265px; overflow:hidden; padding: 15px;\"");

WriteLiteral(" alt=\"設備圖片\"");

WriteLiteral(" /></td>\r\n                </tr>\r\n\r\n                <tr");

WriteLiteral(" class=\"topTaTr\"");

WriteLiteral(">\r\n\r\n                    <td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" id=\"EquipmentID\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" id=\"DAQMachID\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" data-meaning=\"Site\"");

WriteLiteral(">AreaDesc</span>\r\n                    </td>\r\n                    <td");

WriteLiteral(" style=\"width:230px; text-align:left\"");

WriteLiteral("><input");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" disabled");

WriteLiteral(" id=\"AreaDesc\"");

WriteLiteral("></input></td>\r\n                </tr>\r\n                <tr");

WriteLiteral(" class=\"topTaTr\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"Factory\"");

WriteLiteral(">PlantDesc</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px; text-align:left\"");

WriteLiteral("><input");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" disabled");

WriteLiteral(" id=\"PlantDesc\"");

WriteLiteral("></input></td>\r\n                </tr>\r\n                <tr");

WriteLiteral(" class=\"topTaTr\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" style=\"width:150px;\"");

WriteLiteral("><span");

WriteLiteral(" data-meaning=\"MechanicalCondition\"");

WriteLiteral(">Usage</span></td>\r\n                    <td");

WriteLiteral(" style=\"width:230px; text-align:left\"");

WriteLiteral("><input");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" disabled");

WriteLiteral(" id=\"Usage\"");

WriteLiteral("></input><i");

WriteLiteral(" id=\"UsageColor\"");

WriteLiteral(" /></td>\r\n                </tr>\r\n\r\n                <tr>\r\n                    <td");

WriteLiteral(" style=\"width:380px\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"WorkCenter\"");

WriteLiteral(" data-meaning=\"WorkCenter\"");

WriteLiteral(" value=\"WorkCenter\"");

WriteLiteral(" onclick=\"model.WorkCenter()\"");

WriteLiteral(">WorkCenter</button>\r\n\r\n                    </td>\r\n                </tr>\r\n       " +
"         <tr>\r\n                    <td");

WriteLiteral(" style=\"width:380px\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"WorkOrder2\"");

WriteLiteral(" data-meaning=\"WorkOrder2\"");

WriteLiteral(" value=\"WorkOrder2\"");

WriteLiteral(" onclick=\"model.WorkOrder()\"");

WriteLiteral(">WorkOrder</button>\r\n                    </td>\r\n                </tr>\r\n          " +
"      <tr>\r\n                    <td");

WriteLiteral(" style=\"width:380px\"");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"DAQEvent\"");

WriteLiteral(" data-meaning=\"DAQEvent\"");

WriteLiteral(" value=\"DAQEvent\"");

WriteLiteral(" onclick=\"model.DAQEvent()\"");

WriteLiteral(">DAQEvent</button>\r\n                    </td>\r\n                </tr>\r\n           " +
" </table>\r\n            <table");

WriteLiteral(" style=\"border:1px solid #999; \"");

WriteLiteral(">\r\n                <tr>\r\n                    <td");

WriteLiteral(" colspan=\"1\"");

WriteLiteral(" width=\"920\"");

WriteLiteral(" height=\"400\"");

WriteLiteral(" id=\"sensorArea\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"time hide\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" data-meaning=\"MeasureTime\"");

WriteLiteral(">MeasureTime</span>:\r\n                            <span");

WriteLiteral(" id=\"myMeasureTime\"");

WriteLiteral("></span>\r\n                        </div>\r\n                        <div");

WriteLiteral(" id=\"listView\"");

WriteLiteral("></div>\r\n                        <div");

WriteLiteral(" id=\"pager\"");

WriteLiteral(" class=\"k-pager-wrap hide\"");

WriteLiteral("></div>\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n" +
"        </div>\r\n    </div>\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/x-kendo-template\"");

WriteLiteral(" id=\"template\"");

WriteLiteral(">\r\n    <div class=\"product\">\r\n        <img src=\"");

            
            #line 82 "..\..\Views\IntelligentCouplet\IOT00002Machine.cshtml"
             Write(Url.Content("~/content/images/drawimage/trend.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" onclick=""model.showChart( '#:DAQMachID#', '#:Sensor#')"" title=""趨勢圖"" style=""top:15px;right:5px;position:absolute;cursor:pointer;width:30px;height:30px;"" />
        <table width=""100%"" class=""equipment-table v-table"" style=""background-color:#:(MaxAlarmValue!=null&&MinAlarmValue!=null&&MinAlarmValue<=Measurement && Measurement<=MaxAlarmValue)?"" \\#fa7575"":""""#"">
            <tr>
                <td style=""text-align:right;""><span data-meaning=""SensorNo"">Sensor</span>：</td>
                <td style=""text-align:left;"">#:Sensor#</td>

            </tr>
            <tr>
                <td style=""text-align:right;""><span data-meaning=""SensorDescription"">SensorDescription</span>：</td>
                <td style=""text-align:left"">#:SensorDesc#</td>
            </tr>
            <tr>
                <td style=""text-align:right;""><span data-meaning=""PresentValue"">Measurement</span>：</td>
                <td style=""text-align:left"">#:Measurement#</td>
            </tr>
            <tr>
                <td colspan=""2"" height=""60px""><div id=""gauge-container""><div id=""gauge_#:Sensor#""></div></div></td>
            </tr>

        </table>
    </div>
</script>
<!--趨勢圖開窗-->
<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ChartDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:940px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"TrendChart\"");

WriteLiteral(">趨勢圖</h6>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" id=\"table-bodycode\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(" width=\"920\"");

WriteLiteral(" height=\"400\"");

WriteLiteral(">\r\n                <canvas");

WriteLiteral(" id=\"myChart\"");

WriteLiteral("></canvas>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"EquipmentDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"EquipmentMasterFile\"");

WriteLiteral(">EquipmentMasterFile</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"J-search\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"EquipmentCode\"");

WriteLiteral(">EquipmentCode</span>\r\n                <input");

WriteLiteral(" id=\"Code\"");

WriteLiteral(" name=\"Code\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"search-input\"");

WriteLiteral(" style=\"width: 170px;\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(" />\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" onclick=\"model.CodeSearch()\"");

WriteLiteral(" id=\"Find\"");

WriteLiteral(" data-meaning=\"Search\"");

WriteLiteral(" value=\"Search\"");

WriteLiteral(">Search</button>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"table-bodycode\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"EquipmentTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionEquipmentBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"EquipmentCommit\"");

WriteLiteral(" data-meaning=\"Comfirm\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(" value=\"Comfirm\"");

WriteLiteral(">Commit</button>\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"WorkCenterDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:700px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"WorkCenter\"");

WriteLiteral(">WorkCenter</h6>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" id=\"wWC\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"WorkCenterTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionWorkCenterBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"ProcessDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearProcess()\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"ProcessRelating\"");

WriteLiteral(">ProcessRelating</h6>\r\n            </div>\r\n            <div");

WriteLiteral(" style=\"padding: 15px 15px !important;\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" data-meaning=\"WorkCenterNo\"");

WriteLiteral(">WorkCenterCode</span>\r\n                <input");

WriteLiteral(" id=\"WorkCenterCode\"");

WriteLiteral(" disabled /> &nbsp;&nbsp; &nbsp;&nbsp;\r\n                <span");

WriteLiteral(" data-meaning=\"WorkCenterDescription\"");

WriteLiteral(">WorkCenterDesc</span>\r\n                <input");

WriteLiteral(" id=\"WorkCenterDesc\"");

WriteLiteral(" disabled />\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"wPro\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"ProcessTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionProcessBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearProcess()\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"WorkOrderDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:700px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"WorkOrder2\"");

WriteLiteral(">WorkOrder</h6>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" id=\"wWO\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"WorkOrderTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionWorkOrderBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal inmodal\"");

WriteLiteral(" id=\"DAQEventDialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" style=\"width:600px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content animated bounceInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding:16px !important\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"close\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(" data-meaning=\"Close\"");

WriteLiteral(">Close</span>\r\n                </button>\r\n                <h6");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" data-meaning=\"DAQEvent\"");

WriteLiteral(">DAQEvent</h6>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" id=\"wDaq\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"DAQEventTable\"");

WriteLiteral("></table>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"datagrid-pager page\"");

WriteLiteral(" id=\"paginagionDAQEventBar\"");

WriteLiteral(" style=\"margin:0 15px;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"text-align:right;\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" id=\"cancel\"");

WriteLiteral(" onclick=\"model.clearInput(\'#Code\')\"");

WriteLiteral(" data-meaning=\"Cancel\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral(">Cancel</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <style>\r\n        .time {\r\n            width: 100%;\r\n            height: 20p" +
"x;\r\n            text-align: left;\r\n            line-height: 12px;\r\n            f" +
"ont-size: 12px;\r\n            color: #676a6c;\r\n            padding-left: 28px;\r\n " +
"           margin: 8px 2px;\r\n            /*margin-left:20px;*/\r\n        }\r\n\r\n   " +
"     .topTab {\r\n            border: 1px solid #999;\r\n            border-bottom: " +
"none;\r\n            min-height: 280px;\r\n            text-align: center;\r\n        " +
"}\r\n\r\n\r\n        img[src=\"\"] {\r\n            display: none;\r\n            opacity: 0" +
";\r\n        }\r\n\r\n        #WorkCenterCode, #WorkCenterDesc {\r\n            width: 1" +
"10px;\r\n        }\r\n\r\n        .product {\r\n            float: left;\r\n            po" +
"sition: relative;\r\n            width: 400px;\r\n            height: 160px;\r\n      " +
"      margin: 0 25px;\r\n            padding: 0;\r\n        }\r\n\r\n            .produc" +
"t table tr td {\r\n                height: 24px;\r\n                line-height: 24p" +
"x;\r\n            }\r\n\r\n        .hide {\r\n            display: none;\r\n        }\r\n\r\n " +
"       .v-table {\r\n            display: table;\r\n            margin: 0 2%;\r\n     " +
"       border: 1px solid #999;\r\n            height: 150px;\r\n            /*margin" +
"-left: 29px;*/\r\n        }\r\n\r\n\r\n\r\n        #UsageColor {\r\n            display: inl" +
"ine-block;\r\n            width: 27px;\r\n            height: 27px;\r\n            ove" +
"rflow: hidden;\r\n            border-radius: 50%;\r\n            position: relative;" +
"\r\n            bottom: -10px;\r\n        }\r\n\r\n        .topTaTr {\r\n            margi" +
"n-top: 25px;\r\n        }\r\n\r\n        .mf-table-wrapper {\r\n            overflow-x: " +
"auto;\r\n        }\r\n\r\n        #wWO .fix-table, #wWO .fix-head {\r\n            width" +
": 320%;\r\n        }\r\n\r\n        #wPro .fix-table, #wPro .fix-head {\r\n            w" +
"idth: 100%;\r\n        }\r\n\r\n        #wWC .fix-table, #wWC .fix-head {\r\n           " +
" width: 100%;\r\n        }\r\n\r\n        #wDaq .fix-table, #wDaq .fix-head {\r\n       " +
"     width: 100%;\r\n        }\r\n\r\n        select {\r\n            height: 25.5px;\r\n " +
"           font-size: 12px;\r\n            color: #555;\r\n            background-co" +
"lor: #fff;\r\n            background-image: none;\r\n            border: 1px solid #" +
"ccc;\r\n            border-radius: 4px;\r\n            -webkit-box-shadow: inset 0 1" +
"px 1px rgba(0,0,0,.075);\r\n            box-shadow: inset 0 1px 1px rgba(0,0,0,.07" +
"5);\r\n            -webkit-transition: border-color ease-in-out .15s,-webkit-box-s" +
"hadow ease-in-out .15s;\r\n            -o-transition: border-color ease-in-out .15" +
"s,box-shadow ease-in-out .15s;\r\n            transition: border-color ease-in-out" +
" .15s,box-shadow ease-in-out .15s;\r\n        }\r\n    </style>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17148), Tuple.Create("\"", 17205)
, Tuple.Create(Tuple.Create("", 17154), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/hplus/plugins/layer/laydate/laydate.js")
, 17154), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17229), Tuple.Create("\"", 17274)
, Tuple.Create(Tuple.Create("", 17235), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/knockout/knockout-3.0.0.js")
, 17235), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17321), Tuple.Create("\"", 17361)
, Tuple.Create(Tuple.Create("", 17327), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/pagination.js")
, 17327), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17408), Tuple.Create("\"", 17444)
, Tuple.Create(Tuple.Create("", 17414), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Rander.js")
, 17414), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17491), Tuple.Create("\"", 17528)
, Tuple.Create(Tuple.Create("", 17497), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/Checker.js")
, 17497), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17575), Tuple.Create("\"", 17610)
, Tuple.Create(Tuple.Create("", 17581), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/current/table.js")
, 17581), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17657), Tuple.Create("\"", 17711)
, Tuple.Create(Tuple.Create("", 17663), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/hplus/plugins/chartJs/Moment.min.js")
, 17663), false)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 17737), Tuple.Create("\"", 17790)
, Tuple.Create(Tuple.Create("", 17743), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/hplus/plugins/chartJs/Chart.min.js")
, 17743), false)
);

WriteLiteral("></script>\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 17814), Tuple.Create("\"", 17872)
, Tuple.Create(Tuple.Create("", 17821), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/plugins/kendo-ui/kendo.common.min.css")
, 17821), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 17904), Tuple.Create("\"", 17963)
, Tuple.Create(Tuple.Create("", 17911), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/plugins/kendo-ui/kendo.default.min.css")
, 17911), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 17995), Tuple.Create("\"", 18061)
, Tuple.Create(Tuple.Create("", 18002), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/plugins/kendo-ui/kendo.default.mobile.min.css")
, 18002), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 18095), Tuple.Create("\"", 18153)
, Tuple.Create(Tuple.Create("", 18101), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/hplus/plugins/kendo-ui/kendo.all.min.js")
, 18101), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 18177), Tuple.Create("\"", 18237)
, Tuple.Create(Tuple.Create("", 18183), Tuple.Create<System.Object, System.Int32>(Href("~/ViewModels/MES/IntelligentCouplet/IOT00002Machine.js")
, 18183), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
