#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Main.cshtml")]
    public partial class _Views_Home_Main_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Main_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Home\Main.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral(@"

<script>
    function logout() {
        sessionStorage.clear();
        window.location.href = ""/Logon"";
    }

    var token = sessionStorage.getItem('token');
    (function Authorize() {
        if (!token) {
            logout();
        }
    })();

    var language = sessionStorage.getItem(""language"");
    var username = sessionStorage.getItem(""username"");
    var promptBtn, tips;
    function setProgram(text) {
        var arr = text.split('/');
        if (arr[arr.length - 1] == ""Wellcome"") {
            document.getElementById(""program"").innerHTML = """";
            return;
        }
        document.getElementById(""program"").innerHTML = ""PN: "" + arr[arr.length - 1];
    }
</script>

<!DOCTYPE html>

<html>
<head>
    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\"");

WriteLiteral(">\r\n    <title>MES System</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 956), Tuple.Create("\"", 996)
, Tuple.Create(Tuple.Create("", 963), Tuple.Create<System.Object, System.Int32>(Href("~/Content/images/logo/favicon.ico")
, 963), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1051), Tuple.Create("\"", 1104)
, Tuple.Create(Tuple.Create("", 1058), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/font-awesome.min93e3.css?v=4.4.0")
, 1058), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1134), Tuple.Create("\"", 1170)
, Tuple.Create(Tuple.Create("", 1141), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/animate.min.css")
, 1141), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1200), Tuple.Create("\"", 1229)
, Tuple.Create(Tuple.Create("", 1207), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/icon.css")
, 1207), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1263), Tuple.Create("\"", 1309)
, Tuple.Create(Tuple.Create("", 1269), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/jquery/jquery-1.10.2.min.js")
, 1269), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 44 "..\..\Views\Home\Main.cshtml"
Write(System.Web.Optimization.Scripts.Render("~/Content/js/index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <style>\r\n        body {\r\n            margin: 0;\r\n            font-size: 12p" +
"x;\r\n        }\r\n        .view-topbar {\r\n            position: fixed;\r\n           " +
" width: 100%;\r\n            height: 36px;\r\n            background: #3c8dbc;\r\n    " +
"    }\r\n        .view-body {\r\n            position: absolute;\r\n            width:" +
" 100%;\r\n            top: 36px;\r\n            bottom: 0px;\r\n            background" +
"-color: #fff;\r\n        }\r\n        .view-sidebar {\r\n            width: 0px;\r\n    " +
"        display: none;\r\n            position: fixed;\r\n            top: 36px;\r\n  " +
"          bottom: 0px;\r\n            background-color: #065f93;\r\n            over" +
"flow-x: hidden;\r\n        }\r\n        .view-sidebar-mini {\r\n            width: 50p" +
"x;\r\n            display: block;\r\n        }\r\n        .view-sidebar-full {\r\n      " +
"      width: 180px;\r\n            display: block;\r\n        }\r\n        .view-page " +
"{\r\n            width: auto;\r\n            position: absolute;\r\n            top: 0" +
"px;\r\n            left: 0px;\r\n            bottom: 0px;\r\n            right: 0px;\r\n" +
"            background: #fff;\r\n        }\r\n        .view-page-full {\r\n           " +
" width: calc(100% - 50px);\r\n            left: 50px;\r\n        }\r\n        .view-pa" +
"ge-mini {\r\n            width: calc(100% - 180px);\r\n            left: 180px;\r\n   " +
"     }\r\n        .view-sidebar .sidebar-fold {\r\n            height: 30px;\r\n      " +
"      width: 100%;\r\n            background: #4A5064;\r\n            color: #aeb9c2" +
";\r\n            text-align: center;\r\n            line-height: 30px !important;\r\n " +
"           cursor: pointer;\r\n        }\r\n\r\n        .view-topbar-info {\r\n         " +
"   color: #fff;\r\n            text-align:right;\r\n            margin:8px 10px;\r\n  " +
"      }\r\n            .view-topbar-info span {\r\n                margin-right: 16p" +
"x;\r\n            }\r\n            .view-topbar-info .view-topbar-btn {\r\n           " +
"     cursor: pointer;\r\n            }\r\n\r\n        .view-page-content {\r\n          " +
"  display:block;\r\n            height: calc(100% - 26px);\r\n        }\r\n        .vi" +
"ew-page-footer {\r\n            border-top: 1px solid #e7eaec;\r\n            paddin" +
"g: 4px 5px 3px;\r\n            color: #676a6c;\r\n        }\r\n    </style>\r\n</head>\r\n" +
"<body>\r\n    <div");

WriteLiteral(" class=\"view-topbar\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"view-topbar-info\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"view-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"view-sidebar view-sidebar-full\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"sidebar-fold fa fa-bars\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"view-sidebar-nav\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"view-page view-page-mini\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"view-page-content\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"view-page-footer\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" id=\"program\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(" id=\"copyright\"");

WriteLiteral("></div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n<scrip" +
"t>\r\n    $(\".sidebar-fold\").click(function () {\r\n        if ($(\".view-sidebar\").h" +
"asClass(\"view-sidebar-full\")) {\r\n            $(\".view-sidebar\").removeClass(\"vie" +
"w-sidebar-full\");\r\n            $(\".view-sidebar\").addClass(\"view-sidebar-mini\");" +
"\r\n            $(\".view-page\").removeClass(\"view-page-mini\");\r\n            $(\".vi" +
"ew-page\").addClass(\"view-page-full\");\r\n        }\r\n        else {\r\n            $(" +
"\".view-sidebar\").removeClass(\"view-sidebar-mini\");\r\n            $(\".view-sidebar" +
"\").addClass(\"view-sidebar-full\");\r\n            $(\".view-page\").removeClass(\"view" +
"-page-full\");\r\n            $(\".view-page\").addClass(\"view-page-mini\");\r\n        " +
"}\r\n    });\r\n\r\n    //切换页面模式\r\n    function changeModel() {\r\n        window.locatio" +
"n.href = \"/Home\";\r\n    }\r\n\r\n    //获取翻译信息\r\n    function getField(url, name) {\r\n  " +
"      if (!language || !(url && name)) {\r\n            return;\r\n        }\r\n      " +
"  var data;\r\n        var url = url + \"/\" + name + \"-\" + language + \".js\";\r\n     " +
"   $.ajax({\r\n            url: url,\r\n            async: false,\r\n            dataT" +
"ype: \'json\',\r\n            success: function (items) {                    \r\n     " +
"           data = items;\r\n            },\r\n            error: function (data) {\r\n" +
"                console.error(\"GetField: can\'t get \" + url + \":\" + name);\r\n     " +
"       }\r\n        });   \r\n        return data;\r\n    };\r\n\r\n    $(document).ready(" +
"function () {\r\n        var fields = getField(\"/Data/options/home\", \"home\");\r\n   " +
"     mf.ajax({\r\n            type: \'get\',\r\n            url: \'/Util/GetCom" +
"pany\',\r\n            success: function (data) {\r\n                var info = \"\";\r\n" +
"                info += \'<span>\' + fields.UserName + username + \'</span>\';\r\n    " +
"            info += \'<span>\'+ fields.CompanyNo +data.Code+\'</span>\';\r\n          " +
"      info += \'<span>\'+ fields.CompanyName +data.Name+\'</span>\';\r\n              " +
"  info += \'<span class=\"view-topbar-btn\" onclick=\"changeModel()\"><i class=\"fa fa" +
"-exchange\"></i> \'+fields.Exchange+\'</span>\';\r\n                info += \'<span cla" +
"ss=\"view-topbar-btn\" onclick=\"logout()\"><i class=\"fa fa fa-sign-out\"></i> \'+fiel" +
"ds.Logout+\'</span>\';\r\n                $(\".view-topbar-info\").html(info);\r\n      " +
"          $(\"#copyright\").html(\'<span>&copy; \' + fields.Copyright + \'</span>\');\r" +
"\n            }\r\n        });\r\n    });\r\n</script>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
